# Generated by Django 3.0.5 on 2020-04-24 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbloc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbloc.Plan'),
        ),
    ]
