# Generated by Django 3.0.5 on 2020-04-24 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('level', models.IntegerField(default=0, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('address', models.TextField(blank=True, default='', max_length=1000)),
                ('url', models.CharField(blank=True, default='', max_length=1000)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loc.Plan')),
            ],
            options={
                'ordering': ('level',),
            },
        ),
        migrations.CreateModel(
            name='Teleport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('text', models.CharField(default='', max_length=200)),
                ('dest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='loc.Plan')),
                ('src', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teleports', to='loc.Plan')),
            ],
            options={
                'ordering': ('text',),
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('parent', 'level'), name='unique_level'),
        ),
    ]
