# Generated by Django 3.0.5 on 2020-04-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0002_auto_20200416_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='floor',
            name='levels',
            field=models.CharField(default='', max_length=200),
        ),
    ]
