# Generated by Django 3.0.5 on 2020-04-24 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0002_auto_20200424_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loc.Plan'),
        ),
    ]
