# Generated by Django 3.0.5 on 2020-04-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0003_auto_20200416_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
