# Generated by Django 3.0.5 on 2020-04-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0004_floor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='levels',
        ),
        migrations.AddField(
            model_name='floor',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
