# Generated by Django 3.0.5 on 2020-04-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0005_auto_20200418_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('building', 'level'), name='unique_level'),
        ),
    ]
