# Generated by Django 3.0.5 on 2020-04-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0006_auto_20200418_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
