# Generated by Django 3.0.5 on 2020-04-19 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0007_building_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teleport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('text', models.CharField(default='', max_length=200)),
                ('src_building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teleports', to='loc.Building')),
                ('src_floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teleports', to='loc.Floor')),
            ],
        ),
    ]
