# Generated by Django 3.0.5 on 2020-04-19 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0008_teleport'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleport',
            name='target_building',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='loc.Building'),
        ),
    ]
