# Generated by Django 3.0.5 on 2020-04-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0012_auto_20200419_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleport',
            name='dest_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='loc.Building'),
        ),
        migrations.AlterField(
            model_name='teleport',
            name='dest_floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='loc.Floor'),
        ),
    ]
