# Generated by Django 3.0.5 on 2020-04-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0014_auto_20200419_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='building',
            name='url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
