# Generated by Django 3.0.5 on 2020-04-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0015_auto_20200419_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
